// <auto-generated />
namespace Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sinDetalleParcial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sinDetalleParcial));
        
        string IMigrationMetadata.Id
        {
            get { return "202204282153376_sinDetalleParcial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
